apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.Name }}-nfs-volume
  namespace: {{ .Values.Namespace }}
  labels:
    directory: {{ .Values.Name }}
spec:
  capacity:
    storage: {{ .Values.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
  nfs:
    path: {{ .Values.path }}
    server: 10.43.0.4