apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}-service
  namespace: {{ .Values.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.Name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.nodePort }}
      targetPort: {{ .Values.containerPort }}